encoding: utf-8
#safe:        false
#auto:        false
#server:      false
#server_port: 4000
#baseurl:     http://mattn.github.io
title:        Screw It!

include: [".well-known"]
exclude: ["scripts"]

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed

feed:
    title: Screw It!

timezone: Asia/Tokyo
future: true
